name: jouhakka_forge
description: "Do responsive app and web design 10x faster with Jouhakka Forge."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  analyzer: ^7.3.0
  build: ^2.4.2
  build_runner: ^2.4.15
  flutter:
    sdk: flutter
  lucide_icons_flutter: ^1.2.6
  popover: ^0.3.1
  source_gen: ^2.0.0
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

