name: jouhakka_forge
description: "Do responsive app and web design 10x faster with Jouhakka Forge."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  analyzer: ^7.3.0
  build: ^2.4.2
  build_runner: ^2.4.15
  flutter:
    sdk: flutter
  lucide_icons_flutter: ^2.0.1
  popover: ^0.3.1
  source_gen: ^2.0.0
  vector_math: ^2.1.4
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: SometypeMono
      fonts:
        - asset: assets/fonts/SometypeMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/SometypeMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/SometypeMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SometypeMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/SometypeMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SometypeMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/SometypeMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/SometypeMono-BoldItalic.ttf
          weight: 700
          style: italic
